docker compose.yml fixed and updated

diff --git a/Backend/Dockerfile b/Backend/Dockerfile
--- a/Backend/Dockerfile
+++ b/Backend/Dockerfile
@@ -1,34 +1,44 @@
 # syntax=docker/dockerfile:1
 
-# Comments are provided throughout this file to help you get started.
-# If you need more help, visit the Dockerfile reference guide at
-# https://docs.docker.com/go/dockerfile-reference/
-
-# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7
 
 ARG NODE_VERSION=24.8.0
 
 ################################################################################
 # Use node image for base image for all stages.
-FROM node:${NODE_VERSION}-alpine as base
+FROM node:${NODE_VERSION}-alpine AS base
 
 # Set working directory for all build stages.
-WORKDIR /usr/src/app
+WORKDIR  /app
 
 # Copy package.json so that package manager commands can be used.
-COPY package.json .
+COPY package*.json ./
 
 #. install dependencies
 RUN npm install
 
 # Copy the rest of the source files into the image.
 COPY . .
+
 # Run the build script.
 RUN npm run build
 
+RUN ls -la  /app && ls -la /app/dist || echo "DIST FOLDER NOT FOUND"
+
+
+#production
+FROM node:${NODE_VERSION}-alpine
+
+WORKDIR /app
+
+COPY package*.json  ./
+
+RUN npm install --only=production
+
+COPY --from=base /app/dist ./dist
+
 
 # Use production node environment by default.
-ENV NODE_ENV production
+ENV NODE_ENV=production
 
 
 
@@ -37,4 +47,4 @@ ENV NODE_ENV production
 EXPOSE 5000
 
 # Run the application.
-CMD npm start
+CMD ["npm", "start"]
